### ISSUE TITLE
https://github.com/ethereum/go-ethereum/issues/3793

### ISSUE THREAD

**Issue by wbluv** [tomw1808/truffle_eth_class2#2]
Hi Tom, given the deprecation of eth_compileSolidity with geth v1.6.0 +, have you considered updating the course?

https://github.com/ethereum/go-ethereum/issues/3793

I can understand if you are busy and don't have the time. This is great stuff and a good contribution to the ecosystem!

Will

**Comment by tomw1808** [comment]
@wbluv absolutely! The fast pace of the Ethereum Ecosystem is a bit overwhelming.

We are currently preparing a new course and collecting necessary changes for this course.  Once the new course is ready we'll improve this one as well.

If its completely new videos or additional videos or announcements is something we'll discuss internally once we have all the necessary changes.

I'll leave that open. Obviously other changes are welcome here as issues as well.

**Comment by kirabas** [comment]
Hi Tom,
I have started the course but json file from this depository is not working. It even looks different fronm the one you describe in the course.
Please check it

**Comment by tomw1808** [comment]
@kirabas 
the genesis.json file here works just fine for me. Please use the Q&A in the course for more specific questions and post also some more informaton what exactly is not working for you. Thanks
